version: '3'
services:
  ghi:
    image: node:lts-bullseye
    command: ./run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: true

  monolith:
    build:
      context: ./monolith
      dockerfile: Dockerfile.dev
    environment:
      DJWTO_SIGNING_KEY: abcedef
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./monolith:/app
    ports:
      - 8000:8000
