/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Truck(props) {
  const { nodes, materials } = useGLTF("/models/truck.glb");
  return (
    <group {...props} dispose={null} >
      <group name="cab" position={[0, 1.6747, 0]}>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.gray}
        />
        <mesh
          name="Cube_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.windows}
        />
      </group>
      <group name="bed" position={[0, 1.7747, 6.3]}>
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.gray}
        />
        <mesh
          name="Cube002_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.gray}
        />
      </group>
      <mesh
        name="rear_wheel_flares"
        castShadow
        receiveShadow
        geometry={nodes.rear_wheel_flares.geometry}
        material={materials.black}
        position={[0.11737, 2.2747, 7.3728]}
      />
      <group name="right_mirror" position={[2.3, 3.00286, 2]} scale={0.3}>
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube004_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.windows}
        />
      </group>
      <group
        name="left_mirror"
        position={[-2.3, 3.00286, 2]}
        rotation={[-Math.PI, 0, 0]}
        scale={-0.3}
      >
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube005_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.windows}
        />
      </group>
      <mesh
        name="door_handle_right"
        castShadow
        receiveShadow
        geometry={nodes.door_handle_right.geometry}
        material={materials.black}
        position={[2.1, 2.47547, 3.8]}
        scale={0.2}
      />
      <mesh
        name="door_handle_left"
        castShadow
        receiveShadow
        geometry={nodes.door_handle_left.geometry}
        material={materials.black}
        position={[-2.1, 2.47547, 3.8]}
        rotation={[-Math.PI, 0, 0]}
        scale={-0.2}
      />
      <group name="rear_wheel_flares001" position={[0.11737, 2.2747, 0.4]}>
        <mesh
          name="Cube008"
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials.gray}
        />
        <mesh
          name="Cube008_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.black}
        />
      </group>
      <group
        name="headlight_right"
        position={[1.5, 2.27547, -0.7]}
        scale={[0.42, 0.21, 0.3]}
      >
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube011_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials.c_headlight}
        />
      </group>
      <group
        name="headlight_left"
        position={[-1.5, 2.27547, -0.7]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.42, -0.21, -0.3]}
      >
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube012_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.c_headlight}
        />
      </group>
      <mesh
        name="tailgate_latch"
        castShadow
        receiveShadow
        geometry={nodes.tailgate_latch.geometry}
        material={materials.black}
        position={[0, 2.25195, 10.04356]}
        rotation={[0, -1.57053, 0]}
        scale={0.2}
      />
      <mesh
        name="BezierCurve"
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials.black}
        position={[1.3, 2.87547, 6.9]}
      />
      <mesh
        name="BezierCurve001"
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials.black}
        position={[-1.3, 2.87547, 6.9]}
      />
      <mesh
        name="BezierCurve002"
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002.geometry}
        material={materials.black}
        position={[0.00833, 3.23321, 5.6]}
      />
      <group name="light_bar" position={[1.3, 4.34825, 5.64265]} scale={0.2}>
        <mesh
          name="Cube014"
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials.black}
        />
        <mesh
          name="Cube014_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials.c_headlight}
        />
      </group>
      <group
        name="wheel_front_right"
        position={[2.1, 0.97503, 0.50047]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1.9, 1.9, 2.47]}
      >
        <mesh
          name="Cylinder002"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.black}
        />
        <mesh
          name="Cylinder002_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.bronze}
        />
      </group>
      <group
        name="wheel_back_right"
        position={[2.1, 0.97503, 7.46221]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1.9, 1.9, 2.47]}
      >
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.black}
        />
        <mesh
          name="Cylinder006_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.bronze}
        />
      </group>
      <group
        name="wheel_front_left"
        position={[-2.15145, 0.97503, 0.50047]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[-1.9, -1.9, -2.47]}
      >
        <mesh
          name="Cylinder007"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.black}
        />
        <mesh
          name="Cylinder007_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.bronze}
        />
      </group>
      <group
        name="wheel_back_left"
        position={[-2.15145, 0.97503, 7.46221]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[-1.9, -1.9, -2.47]}
      >
        <mesh
          name="Cylinder008"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials.black}
        />
        <mesh
          name="Cylinder008_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.bronze}
        />
      </group>
      <mesh
        name="front_axel"
        castShadow
        receiveShadow
        geometry={nodes.front_axel.geometry}
        material={materials.black}
        position={[0, 0.9861, 0.5]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.1, 1.7, 0.1]}
      />
      <mesh
        name="back_axel"
        castShadow
        receiveShadow
        geometry={nodes.back_axel.geometry}
        material={materials.black}
        position={[0, 0.98498, 7.46]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.1, 1.7, 0.1]}
      />
      <mesh
        name="running_board_left"
        castShadow
        receiveShadow
        geometry={nodes.running_board_left.geometry}
        material={materials.black}
        position={[-2.5, 1.03333, 5.6]}
        rotation={[-Math.PI, 0, 0]}
        scale={-0.1}
      />
      <mesh
        name="running_board_right"
        castShadow
        receiveShadow
        geometry={nodes.running_board_right.geometry}
        material={materials.black}
        position={[2.53333, 1.03333, 5.6]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/models/truck.glb");
