# Generated by Django 4.2.2 on 2023-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerhighscore',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
