# Generated by Django 4.2.2 on 2023-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_multiplayer_alter_playerhighscore_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleshipMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_board', models.JSONField()),
                ('player_two_board', models.JSONField()),
            ],
        ),
    ]
