# Generated by Django 4.2.2 on 2023-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_battleshipmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_one_board',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_two_board',
            field=models.JSONField(default=list),
        ),
    ]
