# Generated by Django 4.2.2 on 2023-07-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='nnnnnnnnn0', max_length=10)),
            ],
        ),
    ]
