# Generated by Django 4.2.2 on 2023-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_battleshipmatch_player_one_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_one_board',
            field=models.JSONField(default=['          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ']),
        ),
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_two_board',
            field=models.JSONField(default=['          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ', '          ']),
        ),
    ]
