# Generated by Django 4.2.2 on 2023-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_battleshipmatch_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleshipmatch',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
