# Generated by Django 4.2.2 on 2023-07-27 23:43

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_battleshipmatch_player_one_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_one_board',
            field=models.JSONField(default=games.models.setup_game_board),
        ),
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_one_count',
            field=models.JSONField(default=games.models.get_initial_counts),
        ),
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_two_board',
            field=models.JSONField(default=games.models.setup_game_board),
        ),
        migrations.AlterField(
            model_name='battleshipmatch',
            name='player_two_count',
            field=models.JSONField(default=games.models.get_initial_counts),
        ),
    ]
