# Generated by Django 4.2.2 on 2023-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_battleshipmatch_player_one_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gif',
        ),
        migrations.AddField(
            model_name='game',
            name='picture_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='picture_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='picture_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='picture_4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
